#Dockerfile for kingtech Markdown2Markup documentation image

FROM kingtechnl/kingtech.documentary:latest AS base
RUN apk --no-cache add curl icu-libs libcap bash
WORKDIR /app
EXPOSE 80
EXPOSE 443

COPY ["./docs/*", "/docs/"]

ARG TARGETARCH
ENV GeneralSettings_Title="Markdown2Markup" \
    GeneralSettings_InsertHomeItem=true \
    GeneralSettings_HomeUrl="https://www.kingtech.nl" \
    FileSystemSettings_RootDirectory="/docs"

ENTRYPOINT ["dotnet", "KingTech.Web.Markdown2Markup.WebService.dll"]