#Dockerfile for kingtech Markdown2Markup documentation image

FROM kingtechnl/kingtech.documentary:latest AS base
RUN apk --no-cache add curl icu-libs libcap bash
WORKDIR /app
EXPOSE 80
EXPOSE 443

COPY ["./docs/", "/docs/"]

ARG TARGETARCH
ENV GeneralSettings__Title=Markdown2Markup \
    GeneralSettings__InsertHomeItem=true \
    GeneralSettings__HomeUrl=https://www.kingtech.nl \
    FileSystemSettings__RootDirectory=/docs

ENTRYPOINT ["dotnet", "KingTech.Web.Markdown2Markup.WebService.dll"]